title = "Расписание недели"
week = "Четная"
[[schedule]]
name = "Понедельник"
[[schedule.lessons]]
subject = "Информатика"
type = "Практика"
teacher = "Рыбаков Степан Дмитриевич"
place = "Кронверский пр., 49, лит. А"
room = "1338"
startime = "09:50"
endtime = "11:20"

[[schedule.lessons]]
subject = "Информатика"
type = "Практика"
teacher = "Рыбаков Степан Дмитриевич"
place = "Кронверский пр., 49, лит. А"
room = "1338"
startime = "11:30"
endtime = "13:00"

[[schedule.lessons]]
subject = "Основы дискретной математики(базовый уровень)"
type = "Лекция"
teacher = "Поляков Владимир Иванович"
place = "Кронверский пр., 49, лит. А"
room = "2433"
startime = "13:30"
endtime = "15:00"

[[schedule.lessons]]
subject = "Основы дискретной математики(базовый уровень)"
type = "Практика"
teacher = "Поляков Владимир Иванович"
place = "Кронверский пр., 49, лит. А"
room = "2337"
startime = "15:30"
endtime = "17:00"


[[schedule]]
name = "Четверг"
[[schedule.lessons]]
subject = "Программирование"
type = "Практика"
teacher = "Бобрусь Александр Владимирович"
place = "Кронверский пр., 49, лит. А"
room = "1333"
startime = "08:10"
endtime = "09:40"

[[schedule.lessons]]
subject = "Программирование"
type = "Практика"
teacher = "Бобрусь Александр Владимирович"
place = "Кронверский пр., 49, лит. А"
room = "1333"
startime = "09:50"
endtime = "11:20"


